const CHANGE_PAGE_MAIN = 'CHANGE-PAGE_MAIN';
const CHANGE_PAGE_COLLECTION = 'CHANGE-PAGE_COLLECTION';
const CATCH_POKEMON = 'CATCH_POKEMON';
const GO_TO_PROFILE = 'GO_TO_PROFILE';
const GO_TO_PREV_PROFILE = 'GO_TO_PREV_PROFILE';
const GO_TO_NEXT_PROFILE = 'GO_TO_NEXT_PROFILE';
const START_APP = 'START_APP';
const GO_TO_RANDOM_PROFILE = 'GO_TO_RANDOM_PROFILE';
const GO_TO_PREV_PAGE_MAIN = 'GO_TO_PREV_PAGE_MAIN';
const GO_TO_NEXT_PAGE_MAIN = 'GO_TO_NEXT_PAGE_MAIN';
const GO_TO_PREV_PAGE_COLLECTION = 'GO_TO_PREV_PAGE_COLLECTION';
const GO_TO_NEXT_PAGE_COLLECTION = 'GO_TO_NEXT_PAGE_COLLECTION';

export { CHANGE_PAGE_MAIN, CHANGE_PAGE_COLLECTION, CATCH_POKEMON, GO_TO_PROFILE, GO_TO_PREV_PROFILE, GO_TO_NEXT_PROFILE,
START_APP, GO_TO_RANDOM_PROFILE, GO_TO_PREV_PAGE_MAIN, GO_TO_NEXT_PAGE_MAIN, GO_TO_PREV_PAGE_COLLECTION,
    GO_TO_NEXT_PAGE_COLLECTION};