const CHANGE_PAGE_MAIN = 'CHANGE-PAGE_MAIN';
const CHANGE_PAGE_COLLECTION = 'CHANGE-PAGE_COLLECTION';
const CATCH_POKEMON = 'CATCH_POKEMON';

export { CHANGE_PAGE_MAIN, CHANGE_PAGE_COLLECTION, CATCH_POKEMON };